doctrine:
    dbal:
        connections:
            fabric:
                driver: 'sqlsrv'
                url: '%env(resolve:DATABASE_FABRIC_URL)%'
                options:
                    CharacterSet: 'UTF-8'
    orm:
        entity_managers:
            mappings:
                FabricImporter:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/vendor/fastbolt/fabric-importer/src/Entity'
                    prefix: 'Fastbolt\FabricImporter\Entity'
                    alias: FabricImporter